create or replace table fact_sales
as 
select SR.CUSTOMER_ID, SR.ORDER_DATE, SR.ORDER_ID, SR.PRODUCT_ID, SR.QUANTITY, SR.UNIT_PRICE, (SR.QUANTITY*SR.UNIT_PRICE) as total_price
from SALES_DB.Raw.SALES_RAW as SR
join SALES_DB.RAW.CUSTOMERS_RAW CR 
on SR.CUSTOMER_ID = CR.CUSTOMER_ID
join SALES_DB.RAW.PRODUCTS_RAW PR
on SR.PRODUCT_ID = PR.PRODUCT_ID;
